name: Build KDU
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # Entramos a la carpeta Source para ejecutar el MSBuild
      - name: Build KDU Solution
        run: msbuild Source/KDU.sln /p:Configuration=Release /p:Platform=x64
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KDU-Binaries
          # Ajustamos la ruta de salida (KDU usa carpetas específicas según su configuración)
          path: |
            Source/Bin/x64/Release/kdu.exe
            Source/Bin/x64/Release/drv64.dll
