name: Build KDU
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build KDU Solution
        run: msbuild Source/KDU.sln /p:Configuration=Release /p:Platform=x64 -p:PlatformToolset=v143
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KDU-Binaries
          path: |
            **/kdu.exe
            **/drv64.dll
          if-no-files-found: error
